CREATE TABLE users
( id SERIAL PRIMARY KRY,
email VARCHAR(100) UNIQUE NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
is_admin BOOLEAN DEFAULT(false),
created_on DATE NOT NULL);
